# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 07545b2fd4baaf4ffb742e143ab9d93203fce5e2d3a22c79bdae9ebf8dd839c5006faa8ecbe3a2c816fda4ca8ab8da345538dae39889ba46202e1f71afb7b820

test:
  secret_key_base: 94fed68bf666488d5868ceb94ca57cf636db0c1edeababb2eb556eac94caefd1beabfc3549514220ac0c07b1e5f64df7801f2dc1f22409ebd1298bc8453c7cc3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
